app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("products.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),

]

orders/models.py
from django.db import models
from products.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_type = models.PositiveSmallIntegerField(default=None, verbose_name="Тип оплаты")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", blank=True, null=True, verbose_name="Аватар")

    phone_number = models.CharField(max_length=10, blank=True, null=True)
    bonuses = models.DecimalField(verbose_name="Бонусы", default=50, max_digits=7, decimal_places=2)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self) -> str:
        return self.username

orders/forms.py
import re

from django import forms


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ],
    )
    delivery_address = forms.CharField(required=False)
    payment_type = forms.ChoiceField(
        choices=[
            ("0", 0),
            ("1", 1),
            ("2", 2)
        ],
    )

    # Проверка номера телефона
    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if data:
            if not data.isdigit():
                raise forms.ValidationError("Номер телефона должен содержать только цифры")

            pattern = re.compile(r'^\d{10}$')
            if not pattern.match(data):
                raise forms.ValidationError("Неверный формат номера")

        return data

    # Проверка адреса доставки
    def clean_delivery_address(self):
        delivery_address = self.cleaned_data["delivery_address"]

        is_requires_delivery = self.cleaned_data["requires_delivery"]

        if not delivery_address and is_requires_delivery == "1":
            raise forms.ValidationError("Для доставки требуется ввод адреса")

        return delivery_address

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from cart.models import Cart

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from users.models import User
from .payments import PaymentProcessorFactory


@login_required
def create_order(request):
    initial = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }
    if request.user.is_authenticated:
        initial["phone_number"] = request.user.phone_number

    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_type=form.cleaned_data['payment_type'],
                        )

                        # Создать заказанные товары
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточное количество товара {name} на складе\
                                                       \nВ наличии - {product.quantity} шт.')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        # Обработка платежа
                        payment_processor = PaymentProcessorFactory().get_payment_processor(order.payment_type)
                        payment_processor.process_payment(order, cart_items)
                        order.save()

                        # Очистить корзину пользователя после создания заказа
                        cart_items.delete()

                        messages.success(request, 'Заказ оформлен!')
                        return redirect('user:profile')
                    else:
                        initial["is_cart"] = False
            except ValidationError as e:
                messages.warning(request, str(e.message))
                return HttpResponseRedirect(reverse("orders:create_order"))

    else:

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'MTech - Оформление заказа',
        'form': form,
        "order": True,
    }
    if request.user.is_authenticated:
        current_user_bonuses = User.objects.get(username=request.user.username).bonuses
        context["bonuses"] = current_user_bonuses

    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block content %}
	<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
		<div class="container">
			<h3 class="text-center mb-4">Выбранные товары</h3>
			<div class="container" id="cart-items-container">
				<!-- Разметка корзины -->
				{% user_carts request as carts %}

				{% include "cart/includes/included_cart.html" %}
				<!-- Закончилась разметка корзины -->
			</div>
		</div>
		<!-- Детали заказа -->
		<div class="container">
			<h3 class="text-center">Детали заказа</h3>
			<div class="card mb-3">
				<div class="card-body">
					<form action="{% url "orders:create_order" %}" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-6 mb-3">
								<label for="id_first_name" class="form-label">Имя*:</label>
								<input type="text" class="form-control" id="id_first_name"
								       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
								       name="first_name" required>
								{% if form.first_name.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.first_name.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_last_name" class="form-label">Фамилия*:</label>
								<input type="text" class="form-control" id="id_last_name" name="last_name"
								       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
								       required>
								{% if form.last_name.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.last_name.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_phone_number" class="form-label">Номер телефона*:</label>
								<input type="tel" class="form-control" id="id_phone_number" name="phone_number"
								       value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
								       placeholder="В формате: 999-999-99-99"
								       required>
								{% if form.phone_number.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.phone_number.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-12 mb-3">
								<label for="delivery" class="form-label">Способ доставки: </label>
								<div class="form-check form-check-inline">
									<input class="form-check-input" type="radio" name="requires_delivery"
									       id="id_requires_delivery" value="1" checked>
									<label class="form-check-label" for="id_requires_delivery">Нужна
										доставка</label>
								</div>
								<div class="form-check form-check-inline">
									<input class="form-check-input" type="radio" name="requires_delivery"
									       id="id_requires_delivery" value="0">
									<label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
								</div>
							</div>
							<div class="mb-3" id="deliveryAddressField">
								<label for="id_delivery_address" class="form-label">Адрес
									доставки*:</label>
								<textarea class="form-control" id="id_delivery_address"
								          value="
										         {% if form.delivery_address.value %}
												{{ form.delivery_address.value }}
												{% endif %}"
								          name="delivery_address" rows="2"></textarea>
								{% if form.delivery_address.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.delivery_address.errors }}</div>
								{% endif %}
							</div>
							<div class="mb-3">
								<label for="id_bonuses" class="form-label" name="bonuses">Ваши бонусы:
									{% if bonuses %}
										{{ bonuses }}
									{% endif %}
								</label>

							</div>
							<div class="col-md-12 mb-3">
								<label class="form-label">Способ оплаты: </label>
								<div class="form-check form-check-inline">
									<input class="form-check-input" type="radio" name="payment_type"
									       id="id_payment_type" value="0" checked>
									<label class="form-check-label" for="id_payment_type">Оплата
										картой</label>
								</div>
								<div class="form-check form-check-inline">
									<input class="form-check-input" type="radio" name="payment_type"
									       id="id_payment_type" value="1">
									<label class="form-check-label" for="id_payment_type">Наличными/картой
										при получении</label>
								</div>
								<div class="form-check form-check-inline">
									<input class="form-check-input" type="radio" name="payment_type"
									       id="id_payment_type" value="2">
									<label class="form-check-label" for="id_payment_type">Бонусами</label>
								</div>
								{% if form.payment_type.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.payment_type.errors }}</div>
								{% endif %}
							</div>
						</div>
						{% if carts.exists %}
							<button type="submit" class="btn btn-dark">Оформить заказ</button>
						{% endif %}

					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}