app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("products.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),

    # path("<slug:category_slug>/<int:page>", views.catalog, name="index"),
    # path("product/<int:product_id>/", views.product, name="product"),
    path("product/<slug:product_slug>/", views.product, name="product"),

]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    # path("users_cart/", views.users_cart, name="users_cart"),
    path("logout/", views.logout, name="logout"),
]

orders/models.py
from django.db import models
from products.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_type = models.PositiveSmallIntegerField(default=None, verbose_name="Тип оплаты")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", blank=True, null=True, verbose_name="Аватар")

    phone_number = models.CharField(max_length=10, blank=True, null=True)
    bonuses = models.DecimalField(verbose_name="Бонусы", default=50, max_digits=7, decimal_places=2)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self) -> str:
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
import re

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        field = ["username", "password"]


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number")

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()

    # Проверка номера телефона
    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")

        return data

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from cart.models import Cart
from orders.models import Order, OrderItem
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("user:logout"):
                    return HttpResponseRedirect(reverse("next"))

                return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {
        'title': 'MTech - Авторизация',
        "form": form,
    }
    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'MTech - Регистрация',
        "form": form
    }
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user) \
        .prefetch_related(
        Prefetch(
            "orderitem_set",
            queryset=OrderItem.objects.select_related("product"),
        )
    ).order_by("-id")

    context = {
        'title': 'MTech - Кабинет',
        "form": form,
        "orders": orders
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse("main:index"))

# def users_cart(request):
#     return render(request, "users/users_cart.html")

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}
{% block content %}
	<div class="row">
		<div class="container mt-5">
			<div class="row p-2">
				<div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
					<h2 class="text-center mb-4">Авторизация</h2>
					<form action="{% url 'user:login' %}" method="post">
						{% csrf_token %}
						{% if request.GET.next %}
							<input type="hidden" name="next" value="{{ request.GET.next }}">
						{% endif %}
						<div class="mb-3">
							<label for="id_username" class="form-label">Имя пользователя</label>
							<input type="text" class="form-control"
							       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
							       name="username" id="id_username"
							       placeholder="Введите ваше имя пользователя"
							       required>
						</div>
						<div class="mb-3">
							<label for="id_password" class="form-label">Пароль</label>
							<input type="password" class="form-control" name="password" id="id_password"
							       placeholder="Введите ваш пароль" required>
						</div>

						<button type="submit" class="btn btn-dark btn-block">Войти</button>
					</form>
					<hr>
					<div class="mt-3">
						{#						<a href="#">Забыли пароль?</a> |#}
						<a href="{% url "user:register" %}">Создать аккаунт</a>
					</div>
					{#					<hr>#}
					{#					<div class="text-center">#}
					{#						<p>Или авторизуйтесь через:</p>#}
					{#						<a href="#" class="btn btn-dark">#}
					{#							<img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16"#}
					{#							     height="16">#}
					{#							Google#}
					{#						</a>#}
					{#						<a href="#" class="btn btn-dark">#}
					{#							<img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16"#}
					{#							     height="16">#}
					{#							Facebook#}
					{#						</a>#}
					{#						<a href="#" class="btn btn-dark">#}
					{#							<img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16"#}
					{#							     height="16">#}
					{#							GitHub#}
					{#						</a>#}
					{#					</div>#}
				</div>
			</div>
		</div>
	</div>
	</div>
	</div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block content %}
	<div class="row">
		<div class="container mt-5">
			<div class="row">
				<!-- Профиль с данными пользователя -->
				<div class="col-md-5">
					<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
						<h3 class="text-center mb-4">Профиль пользователя</h3>
						<form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="row">
								<div class="col-md-12 mb-3 text-center">
									{% if user.image %}
										<img src="{{ user.image.url }}"
										     alt="Аватар пользователя" class="img-fluid rounded-circle"
										     style="max-width: 150px;">
									{% else %}
										<img src="{% static "deps/images/baseavatar.jpg" %}"
										     alt="Аватар пользователя" class="img-fluid rounded-circle"
										     style="max-width: 150px;">
									{% endif %}
									<input type="file" class="form-control mt-3" id="id_image"
									       name='image'
									       accept="image/*">
									{% if form.image.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.image.errors }}</div>
									{% endif %}
								</div>
								<div class="col-md-12 mb-3">
									<label for="id_first_name" class="form-label">Имя*</label>
									<input type="text" class="form-control" id="id_first_name"
									       name="first_name"
									       placeholder="Введите ваше имя"
									       value="{{ form.first_name.value }}"
									       required>
									{% if form.first_name.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.first_name.errors }}</div>
									{% endif %}
								</div>
								<div class="col-md-12 mb-3">
									<label for="id_last_name" class="form-label">Фамилия*</label>
									<input type="text" class="form-control" id="id_last_name"
									       name="last_name"
									       placeholder="Введите вашу фамилию"
									       value="{{ form.last_name.value }}"
									       required>
									{% if form.last_name.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.last_name.errors }}</div>
									{% endif %}
								</div>
								<div class="col-md-12 mb-3">
									<label for="id_username" class="form-label">Имя пользователя*</label>
									<input type="text" class="form-control" id="id_username"
									       name="username"
									       placeholder="Введите ваше имя пользователя"
									       value="{{ form.username.value }}"
									       required>
									{% if form.username.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.username.errors }}</div>
									{% endif %}
								</div>
								<div class="col-md-12 mb-3">
									<label for="id_email" class="form-label">Email*</label>
									<input type="email" class="form-control" id="id_email"
									       name="email"
									       placeholder="Введите ваш email *youremail@example.com"
									       value="{{ form.email.value }}"
									       required>
									{% if form.email.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.email.errors }}</div>
									{% endif %}
								</div>
								<div class="col-md-12 mb-3">
									<label for="id_phone_number" class="form-label">Номер телефона*</label>
									<input type="tel" class="form-control" id="id_phone_number"
									       name="phone_number"
									       placeholder="Номер телефона в формате: 999 999 99 99"
									       value="{{ form.phone_number.value }}">
									{% if form.phone_number.errors %}
										<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.phone_number.errors }}</div>
									{% endif %}
								</div>
							</div>
							<button type="submit" class="btn btn-dark">Сохранить</button>
						</form>
					</div>
				</div>
				<!-- Корзина -->
				{% user_carts request as carts %}
				<div class="col-md-7">
					<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
						<h3 class="text-center mb-4">Корзина</h3>
						<div class="container" id="cart-items-container">
							<!-- Разметка корзины -->
							{% include "cart/includes/included_cart.html" %}
							<!-- Закончилась разметка корзины -->
						</div>

					</div>
				</div>
				<!-- Оформленные заказы -->
				<div class="col-md-12">
					<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
						<h3 class="text-center mb-4">Мои заказы</h3>
						<!-- Разметка заказов -->
						<div class="container">
							<div class="accordion" id="accordionExample">
								{% for order in orders %}
									<div class="accordion-item">
										<h2 class="accordion-header" id="heading{{ order.id }}">
											<button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}"
											        type="button" data-bs-toggle="collapse"
											        data-bs-target="#collapse{{ order.id }}" aria-expanded="false"
											        aria-controls="collapse{{ order.id }}">
												Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong
													class="mx-2">{{ order.status }}</strong>
											</button>
										</h2>
										<div id="collapse{{ order.id }}"
										     class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}"
										     aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
											<div class="accordion-body">
												<table class="table table-secondary table-hover table-striped">
													<thead>
													<tr>
														<th>Товар</th>
														<th>Количество</th>
														<th>Цена</th>
														<th>Общая стоимость</th>
													</tr>
													</thead>
													<tbody>
													{% for item in order.orderitem_set.all %}
														<tr>
															<td>
																<img class="center" src="{{ item.product.image.url }}"
																     width="50px" height="50px">
																<a class="text-dark"
																   href="{% url 'products:product' item.product.slug %}">{{ item.product.name }}</a>
															</td>
															<td>{{ item.quantity }}</td>
															<td>{{ item.price }}</td>
															<td>{{ item.products_price }}</td>

														</tr>
													{% endfor %}
													</tbody>
												</table>
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}
{% block content %}
	<div class="row">
		<div class="container mt-5">
			<div class="row p-2">
				<div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
					<h2 class="text-center mb-4">Регистрация</h2>
					<form action="{% url "user:register" %}" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-6 mb-3">
								<label for="id_first_name" class="form-label">Имя*</label>
								<input type="text" class="form-control" id="id_first_name"
								       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
								       name="first_name"
								       placeholder="Введите ваше имя" required>
								{% if form.first_name.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.first_name.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_last_name" class="form-label">Фамилия*</label>
								<input type="text" class="form-control" id="id_last_name"
								       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
								       name="last_name"
								       placeholder="Введите вашу фамилию" required>
								{% if form.last_name.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.last_name.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_username" class="form-label">Имя пользователя*</label>
								<input type="text" class="form-control" id="id_username"
								       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
								       name="username"
								       placeholder="Введите ваше имя пользователя" required>
								{% if form.username.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.username.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_email" class="form-label">Email*</label>
								<input type="email" class="form-control" id="id_email"
								       value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
								       name="email"
								       placeholder="Введите ваш email" required>
								{% if form.email.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.email.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_password1" class="form-label">Пароль*</label>
								<input type="password" class="form-control" id="id_password1"
								       value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
								       name="password1"
								       placeholder="Введите пароль" required>
								{% if form.password1.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.password1.errors }}</div>
								{% endif %}
							</div>
							<div class="col-md-6 mb-3">
								<label for="id_password2" class="form-label">Подтверждение пароля*</label>
								<input type="password" class="form-control" id="id_password2"
								       value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
								       name="password2"
								       placeholder="Подтвердите пароль" required>
								{% if form.password2.errors %}
									<div class="alert alert-danger alert-dismissible fade show mt-1">{{ form.password2.errors }}</div>
								{% endif %}
							</div>
						</div>
						<button type="submit"
						        class="btn btn-dark btn-block">Зарегистрироваться
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
{% endblock %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block content %}
	{% user_carts request as carts %}
	<div class="row">
		<div class="container mt-5">
			<div class="row justify-content-center">
				<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
					<h3 class="text-center mb-4">Корзина</h3>
					<div class="container" id="cart-items-container">
						<!-- Разметка корзины -->
						{% include "cart/includes/included_cart.html" %}
						<!-- Закончилась разметка корзины -->

					</div>


				</div>
			</div>
		</div>
	</div>
{% endblock %}