app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("products.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),

    # path("<slug:category_slug>/<int:page>", views.catalog, name="index"),
    # path("product/<int:product_id>/", views.product, name="product"),
    path("product/<slug:product_slug>/", views.product, name="product"),

]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    # path("users_cart/", views.users_cart, name="users_cart"),
    path("logout/", views.logout, name="logout"),
]

templates/base.html
{% load static %}
{% load products_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
	<!-- Стиль footer-a для главной страницы -->
	{% block css %}

	{% endblock %}
	<!-- Favicons for different platforms -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
	<link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
	<title>{{ title }}</title>
</head>

<body class="h-100">
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark" data-bs-theme="dark">
		<div class="container">
			<a class="navbar-brand" href="{% url "main:index" %}">MTech</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
			        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
			        aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-1 mb-2 mb-lg-0">
					<li class="nav-item dropdown ">
						<a class="nav-link dropdown-toggle text-white" href="#" role="button"
						   data-bs-toggle="dropdown" aria-expanded="false">
							Информация
						</a>
						<ul class="dropdown-menu  dropdown-menu-dark">
							{#							<li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>#}
							{#							<li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>#}
							<li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
						</ul>
						{#					<li class="nav-item">#}
						{#						<a class="nav-link  text-white" href="{% url "users:users_cart" %}">Корзина</a>#}
						{#					</li>#}
					</li>

				</ul>
				<form class="ms-2 d-flex" role="search" action="{% url "catalog:search" %}" method="get">
					<input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
					<button class="btn btn-outline-primary text-white" type="submit">Поиск</button>
				</form>
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">

					{% if not user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link  text-white bg-primary rounded" href="{% url "user:login" %}">Войти</a>
						</li>
					{% else %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-white" href="#" role="button"
							   data-bs-toggle="dropdown" aria-expanded="false">
								Мой профиль
							</a>
							<ul class="dropdown-menu dropdown-menu-dark">

								<li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный
									кабинет</a>
								</li>
								{% if user.is_admin or user.is_staff %}
									<li><a class="dropdown-item  text-white" href="/admin">Админ панель</a></li>
								{% endif %}

								<li>
									<hr class="dropdown-divider">
								</li>
								<li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
							</ul>
						</li>
					{% endif %}


				</ul>
			</div>
		</div>
	</nav>
</header>
<section>
	<div class="container">
		<!-- Корзина и каталог с фиксированным расположением на странице -->
		<div class="mt-1 position-fixed">
			<!-- Значок корзины, вызывает модальное окно -->
			{% block modal_cart %}

			{% endblock %}
			<!-- Закончилась разметка модального окна -->
			<!-- Каталог -->
			<div class="dropdown mr-5">
				<button class="btn btn-secondary dropdown-toggle btn-dark catalog-dropdown" type="button"
				        data-bs-toggle="dropdown"
				        aria-expanded="false">
					Каталог
					<img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
					     height="16">
				</button>
				<ul class="dropdown-menu bg-dark" data-bs-theme="dark">
					{% tag_categories as categories %}
					{% for category in categories %}
						<li><a class="dropdown-item text-white"
						       href="{% url "catalog:index" category.slug %}">{{ category.name }}</a>
						</li>
					{% endfor %}
				</ul>
			</div>

		</div>
		<!-- Контент -->

		<div class="container h-100">
			<div class="row mt-2">
				<div class="mt-2 col-lg-2">
					<!-- Пустой блок на Ваше усмотрение -->
				</div>
				<div class="col-lg-10 rounded">
					<!-- Контент на странице -->
					{% include "includes/notifications.html" %}
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
	</div>

</section>

{% block footer %}
{% endblock %}

<script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
<script src="{% static "deps/js/jquery-ajax.js" %}"></script>
<script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>