app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("products.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from products import views

app_name = "products"

urlpatterns = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),

    # path("<slug:category_slug>/<int:page>", views.catalog, name="index"),
    # path("product/<int:product_id>/", views.product, name="product"),
    path("product/<slug:product_slug>/", views.product, name="product"),

]

products/models.py
from django.db import models
from decimal import Decimal
from abc import ABC, abstractmethod

from django.contrib.postgres.search import SearchVector, SearchQuery, \
    SearchRank, SearchHeadline

from django.shortcuts import get_list_or_404
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self) -> str:
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="products_images", blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена")
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name="Скидка в процентах")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name="Категория")

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ("id",)

    def __str__(self) -> str:
        return f"{self.name} Количество - {self.quantity}"

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def display_id(self):
        return f"{self.id:05}"

    def round_half_up(self, n, decimals=0):
        multiplier = 10 ** decimals
        return int(n * multiplier + Decimal(0.5)) / multiplier

    def sell_price(self):
        if self.discount:
            return self.round_half_up(self.price - self.price * self.discount / 100, 2)
        return self.price


class IProductFilterStrategy(ABC):
    @abstractmethod
    def filter(self, products):
        pass


class OnSaleFilterStrategy(IProductFilterStrategy):
    def filter(self, products):
        return products.filter(discount__gt=0)


class CategoryFilterStrategy(IProductFilterStrategy):
    def __init__(self, category_slug):
        self.category_slug = category_slug

    def filter(self, products):
        return products.filter(category__slug=self.category_slug)


class SearchFilterStrategy(IProductFilterStrategy):
    def __init__(self, query):
        self.query = query

    def q_search(self):
        if self.query.isdigit() and len(self.query) <= 5:
            return Products.objects.filter(id=int(self.query))

        vector = SearchVector("name", "description")
        query = SearchQuery(self.query)

        result = Products.objects.annotate(rank=SearchRank(vector, query)) \
            .filter(rank__gt=0) \
            .order_by("-rank")
        result = result.annotate(headline=SearchHeadline("name",
                                                         query,
                                                         start_sel="<span style='background-color: cyan'>",
                                                         stop_sel="</span>"))
        result = result.annotate(bodyline=SearchHeadline("description",
                                                         query,
                                                         start_sel="<span style='background-color: cyan'>",
                                                         stop_sel="</span>"))
        return result

    def filter(self, products):
        return self.q_search()


class OrderFilterStraregy(IProductFilterStrategy):
    def __init__(self, order_by):
        self.order_by = order_by

    def filter(self, products):
        return products.order_by(self.order_by)

products/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_list_or_404
from products.models import *


# Create your views here.

def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)
    strategies: list[IProductFilterStrategy] = []
    products = Products.objects.all()

    # Стратегия родненькая
    if query:
        strategies.append(SearchFilterStrategy(query))
    elif category_slug and category_slug != "all":
        strategies.append(CategoryFilterStrategy(category_slug))

    if on_sale:
        strategies.append(OnSaleFilterStrategy())

    if order_by and order_by != "default":
        strategies.append(OrderFilterStraregy(order_by))

    for strategy in strategies:
        products = strategy.filter(products)

    paginator = Paginator(products, 3)
    current_page = paginator.page(page)

    context = {
        "title": "MTech - Каталог",
        "products": current_page,
        "slug_url": category_slug,
    }

    return render(request, "products/catalog.html", context)

    # if category_slug == "all":
    #     products = Products.objects.all()
    # elif query:
    #     products = q_search(query)
    # else:
    #     products = get_list_or_404(Products.objects.filter(category__slug=category_slug))
    #
    # if on_sale:
    #     products = products.filter(discount__gt=0)
    #
    # if order_by and order_by != "default":
    #     products = products.order_by(order_by)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    context = {
        "product": product
    }

    return render(request, "products/product.html", context)

products/templates/products/catalog.html
{% extends "base.html" %}
{% load static %}
{% load products_tags %}

{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}

	<div class="items-catalog custom-shadow p-3 mb-5">
		<div class="row">
			<!-- Форма фильтров -->
			<div class="dropdown mb-2 mt-2 ps-4">
				<button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
				        aria-expanded="false">
					Фильтры
				</button>

				<form action="{% if request.GET.q %}
				{% url "catalog:search" %}{% else %}
				{% url "catalog:index" slug_url %}
				{% endif %}" method="get" class="dropdown-menu bg-dark"
				      data-bs-theme="dark">
					<div class="form-check text-white mx-3">
						<input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
								{% if request.GET.on_sale == "on" %}
                               checked
								{% endif %} >
						{% if request.GET.q %}
							<input type="hidden" name="q" value="{{ request.GET.q }}">
						{% endif %}

						<label class="form-check-label" for="flexCheckDefault">
							Товары по акции
						</label>
					</div>
					<p class="text-white mx-3 mt-3">Сортировать:</p>
					<div class="form-check text-white mx-3">
						<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1"
						       value="default" {% if not request.GET.order_by or request.GET.order_by == "default" %}
						       checked{% endif %}>
						<label class="form-check-label" for="flexRadioDefault1">
							По умолчанию
						</label>
					</div>
					<div class="form-check text-white mx-3">
						<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2"
						       value="price" {% if request.GET.order_by == "price" %}
						       checked
						{% endif %}>
						<label class="form-check-label" for="flexRadioDefault2">
							От дешевых к дорогим
						</label>
					</div>
					<div class="form-check text-white mx-3">
						<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3"
						       value="-price" {% if request.GET.order_by == "-price" %}
						       checked
						{% endif %}>
						<label class="form-check-label" for="flexRadioDefault3">
							От дорогих к дешевым
						</label>
					</div>
					<button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
				</form>
			</div>

			{% if request.GET.q %}
				<h3 class="mt-4">Результаты поиска по запросу {{ request.GET.q }}</h3>
				{% if not products %}
					<link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
					<h2 class="mt-4">По запросу ничего не найдено</h2>
				{% endif %}
			{% endif %}

			{% for product in products %}
				<!-- Карта товара -->
				<div class="col-lg-4 col-md-6 p-4">
					<div class="card border-primary rounded custom-shadow-product">
						{% if product.image %}
							<img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
						{% else %}
							<img src="{% static "deps/images/Not found image.png" %}" class="card-img-top"
							     alt="images not found">
						{% endif %}

						<div class="card-body">
							<a href="{% url "catalog:product" product.slug %}">
								<p class="card-title">
									{% autoescape off %}
										{% if product.headline %}
											{{ product.headline }}
										{% else %}
											{{ product.name }}
										{% endif %}
									{% endautoescape %}
								</p>
							</a>
							<p class="card-text">
								{% autoescape off %}
									{% if product.bodyline %}
										{{ product.bodyline|truncatechars:90 }}
									{% else %}
										{{ product.description|truncatechars:40 }}
									{% endif %}
								{% endautoescape %}
							</p>
							<p class="product_id">id: {{ product.display_id }}</p>
							<div class="d-flex justify-content-between">
								{% if product.discount %}
									<p><s>{{ product.price }}</s> $</p>
									<p><strong>{{ product.sell_price }} $</strong></p>
									<span class="badge bg-info text-dark">Скидка {{ product.discount }} %</span>

								{% else %}
									<p><strong>{{ product.price }} $</strong></p>
								{% endif %}

								<a href="{% url "carts:cart_add" %}" class="btn add-to-cart"
								   data-product-id="{{ product.id }}">
									{% csrf_token %}
									<img class="mx-1"
									     src="{% static "deps/icons/cart-plus.svg" %}"
									     alt="Catalog Icon"
									     width="32" height="32">
								</a>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}

		</div>
		{% if products %}
			<!-- Пагинация -->
			<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center my-4">
					<div class="d-flex">
						<li class="page-item {% if not products.has_previous %} disabled {% endif %}">
							<a class="page-link"
							   href="{% if products.has_previous %}?



								   {% change_params page=products.previous_page_number %}{% else %}#{% endif %}">Назад</a>
						</li>

						{% for page in products.paginator.page_range %}
							{% if page >= products.number|add:-2 and page <= products.number|add:2 %}
								<li class="page-item {% if products.number == page %} active {% endif %}">
									<a class="page-link"
									   href="?{% change_params page=page %}">{{ page }}</a>
								</li>
							{% endif %}
						{% endfor %}


						<li class="page-item {% if not products.has_next %} disabled {% endif %}">
							<a class="page-link"
							   href="{% if products.has_next %}?
								   {% change_params page=products.next_page_number %}{% else %}#{% endif %}">Вперед
							</a>
						</li>

					</div>
				</ul>
			</nav>
		{% endif %}

	</div>

{% endblock %}

{% block footer %}
	<footer class="py-4 bg-dark text-white text-center">
		<div class="container">
			<h4>Есть вопросы? Ответим!</h4>
			<div class="container d-flex flex-column">
				<p>Пишите: <a class="link-light" href="mailto:daniilminakov579@gmail.com">daniilminakov579@gmail.com</a>
				</p>
				<p>Звоните: <a class="link-light" href="tel:79212673425">+79212673425</a> и <a
						class="link-light"
						href="tel:+79212673426">+79212673426</a></p>
			</div>

		</div>


		<div class="container">
			<p class="m-0">Copyright &copy; MTech 2024</p>
		</div>
	</footer>
{% endblock %}

products/templates/products/product.html
{% extends "base.html" %}
{% load static %}
{% block modal_cart %}
	{% include "includes/cart_button.html" %}
{% endblock %}
{% block content %}

	<div class="container m-5">
		<div class="card mb-4 custom-shadow ">
			<div class="row">
				<!-- Миниатюры -->
				<div class="col-md-4 ms-2 mt-2 ">
					<img src="{{ product.image.url }}"
					     class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
				</div>
				<div class="col-md-4 ">
					<p class="product_id mt-3">id: {{ product.display_id }}</p>
				</div>
				<!-- Увеличить изображение в модальном окне -->
				<div class="modal fade" id="imageModal1" tabindex="-1"
				     aria-labelledby="imageModal1Label" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal"
								        aria-label="Закрыть"></button>
							</div>
							<div class="modal-body">
								<img src="{{ product.image.url }}"
								     class="img-fluid" alt="{{ product.name }}">
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Описание товара -->
			<div class="card-body">
				<p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
				<h5 class="card-title">{{ product.name }}</h5>
				<p class="card-text">{{ product.description }}</p>
				<a href="{% url "carts:cart_add" %}" class="btn btn-dark add-to-cart"
				   data-product-id="{{ product.id }}">
					{% csrf_token %}
					Добавить в
					корзину</a>
			</div>
		</div>
	</div>


{% endblock %}

{% block footer %}
{% endblock %}